---
openapi: 3.0.0
info:
  title: EVP-api
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/kuko6/EVP/1.0.0
  description: SwaggerHub API Auto Mocking
- url: localhost:8000/api
paths:
  /project-statuses:
    get:
      tags:
      - project statuses
      summary: Returns an array of possible project statuses
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectStatuses'
  /project-home-types:
    get:
      tags:
      - project home types
      summary: Returns an array of possible project types for home projects
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectHomeTypes'
  /project-foreign-types:
    get:
      tags:
      - project foreign types
      summary: Returns an array of possible project types for foreign projects
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectForeignTypes'
  /project:
    post:
      tags:
      - project
      summary: Creates new project
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/project_body'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewProject'
        "422":
          description: Unprocessable Entity
components:
  schemas:
    ProjectStatuses:
      type: array
      items:
        $ref: '#/components/schemas/ProjectStatuses_inner'
    ProjectHomeTypes:
      type: array
      items:
        $ref: '#/components/schemas/ProjectHomeTypes_inner'
    ProjectForeignTypes:
      type: array
      items:
        $ref: '#/components/schemas/ProjectForeignTypes_inner'
    NewProject:
      type: object
      properties:
        id:
          type: integer
          example: 2132134
    project_milestones:
      type: object
      properties:
        id:
          type: integer
          example: 0
        name:
          type: string
          example: Milnik 1
        description:
          type: string
          example: Nejaky milnik, idk, laldaldaldlal.
        end_date:
          type: string
          format: date-time
    project_outputs:
      type: object
      properties:
        name:
          type: string
          example: Patent
        count:
          type: integer
          example: 2
        milestone_id:
          type: integer
          example: 0
    project_body:
      type: object
      properties:
        type:
          type: string
          example: home
        subtype:
          type: string
          example: KEGA
        name_sk:
          type: string
          example: Názov projektu v slovenčine
        name_eng:
          type: string
          example: Name of the project in english
        abstract:
          type: string
          example: Convolutional neural networks (CNNs) have been applied to various automatic image segmentation tasks in medical image analysis, including brain MRI segmentation...
        keywords:
          type: array
          items:
            type: string
            example: Adversarial networks
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        milestones:
          type: array
          items:
            $ref: '#/components/schemas/project_milestones'
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/project_outputs'
    ProjectStatuses_inner:
      type: object
      properties:
        id:
          type: integer
          example: 2
        status:
          type: string
          example: Pred schválením
    ProjectHomeTypes_inner:
      type: object
      properties:
        id:
          type: integer
          example: 3
        status:
          type: string
          example: Grantový systém
    ProjectForeignTypes_inner:
      type: object
      properties:
        id:
          type: integer
          example: 3
        status:
          type: string
          example: Negrantové zmluvy
