openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'EVP-api'
  description: 'api documentation for the EVP project'
  
servers:
  - description: 'Dev'
    url: 'http://localhost:8000/api'
  - description: 'Production'
    url: 'https://evp-backend.fly.dev/api'
paths:
  /project-statuses:
    get:
      summary: "Returns an array of possible project statuses"
      tags:
        - project statuses
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectStatuses'
                
  /project-home-types:
    get:
      summary: "Returns an array of possible project types for home projects"
      tags:
        - project home types
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectHomeTypes'
                
  /project-foreign-types:
    get:
      summary: "Returns an array of possible project types for foreign projects"
      tags:
        - project foreign types
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectForeignTypes'
                
  /project:
    post:
      summary: 'Creates new project'
      tags:
        - project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: 'home'
                subtype:
                    type: string
                    example: 'KEGA'
                name_sk:
                  type: string
                  example: 'Názov projektu v slovenčine'
                name_eng:
                    type: string
                    example: 'Name of the project in english'
                abstract:
                  type: string
                  example: 'Convolutional neural networks (CNNs) have been applied to various automatic image segmentation tasks in medical image analysis, including brain MRI segmentation...'
                keywords:
                  type: array
                  items:
                    type: string
                    example: "Adversarial networks"
                start_date:
                  type: string
                  format: date-time
                  example: '2020-12-12'
                end_date:
                  type: string
                  format: date-time
                  example: '2021-12-12'
                milestones:
                  type: array
                  items: 
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 0
                      name: 
                        type: string
                        example: 'Milnik 1'
                      description:
                        type: string
                        example: 'Nejaky milnik, idk, laldaldaldlal.'
                      end_date:
                        type: string
                        format: date-time
                        example: '2021-12-12' 
                outputs:
                  type: array
                  items: 
                    type: object
                    properties:
                      name:
                        type: string
                        example: 'Patent'
                      count:
                        type: integer
                        example: 2
                      milestone_id:
                        type: integer
                        example: 0
                        
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewProject'
        '422':
          description: Unprocessable Entity
          #content:
          #  application/json:
          #    schema: 
          #      $ref:  '#/components/schemas/ErrorBadBody' 
                
components:
  schemas:
    ProjectStatuses:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 2
          status:
            type: string
            example: 'Pred schválením'
    
    ProjectHomeTypes:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 3
          status:
            type: string
            example: 'Grantový systém'
      
    ProjectForeignTypes:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 3
          status:
            type: string
            example: 'Negrantové zmluvy'

    NewProject:
      type: object
      properties:
        id: 
          type: integer
          example: 2132134
