openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'EVP-api'
  description: 'api documentation for the EVP project'
  
servers:
  - description: 'Dev'
    url: 'http://localhost:8000/api'
  - description: 'Production'
    url: 'https://evp-backend.fly.dev/api'
paths:
  /user/{id}/projects:
    get:
      summary: "Returns projects of a user specified by ID"
      parameters:
          - in: path
            name: id
            schema:
              type: integer
              example: 1
            required: true
            description: ID of the user
      tags:
        - projects of user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          first_name:
                            type: string
                            example: John
                          last_name:
                            type: string
                            example: Doe
                          email:
                            type: string
                            example: john@doe.com
                          phone_number:
                            anyOf:
                              - type: string
                                example: 0901 234 567
                              - type: null
                          my_projects:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  example: 3
                                type:
                                  type: string
                                  example: domestic
                                subtype:
                                  type: string
                                  example: APPV
                                name_sk:
                                  type: string
                                  example: slovenský názov 3
                                name_en:
                                  type: string
                                  example: english title 3
                                start_date:
                                  type: string
                                  example: 2020-12-12
                                  format: date
                                end_date:
                                  type: string
                                  example: 2022-12-12
                                  format: date
                                is_draft:
                                  type: boolean
                                  example: false
                                status:
                                  type: string
                                  example: V realizácii
                                user_roles:
                                  type: array
                                  items:
                                    type: string
                                    example: project_user
                                user_roles_sk:
                                  type: array
                                  items:
                                    type: string
                                    example: Riešiteľ
                                active_member:
                                  type: boolean
                                  example: true
                          invitations:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  example: 2
                                type:
                                  type: string
                                  example: foreign
                                subtype:
                                  type: string
                                  example: APPV
                                name_sk:
                                  type: string
                                  example: slovenský názov 2
                                name_en:
                                  type: string
                                  example: english title 2
                                start_date:
                                  type: string
                                  example: 2020-12-12
                                  format: date
                                end_date:
                                  type: string
                                  example: 2022-12-12
                                  format: date
                                is_draft:
                                  type: boolean
                                  example: false
                                status:
                                  type: string
                                  example: Podaný
                                user_roles:
                                  type: array
                                  items:
                                    type: string
                                    example: project_user
                                user_roles_sk:
                                  type: array
                                  items:
                                    type: string
                                    example: Riešiteľ
                                active_member:
                                  type: boolean
                                  example: false
                          drafts:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  example: 1
                                type:
                                  type: string
                                  example: domestic
                                subtype:
                                  type: string
                                  example: KEGA
                                name_sk:
                                  type: string
                                  example: slovenský názov 1
                                name_en:
                                  type: string
                                  example: english title 1
                                start_date:
                                  type: string
                                  example: 2020-12-12
                                  format: date
                                end_date:
                                  type: string
                                  example: 2022-12-12
                                  format: date
                                is_draft:
                                  type: boolean
                                  example: true
                                status:
                                  type: string
                                  example: Pred schválením
                                user_roles:
                                  type: array
                                  items:
                                    type: string
                                    example: project_admin
                                user_roles_sk:
                                  type: array
                                  items:
                                    type: string
                                    example: Hlavný riešiteľ
                                active_member:
                                  type: boolean
                                  example: false
        '404':
          description: Not found

  /project-statuses:
    get:
      summary: "Returns an array of possible project statuses"
      tags:
        - project statuses
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectStatuses'
                
  /project-home-types:
    get:
      summary: "Returns an array of possible project types for home projects"
      tags:
        - project home types
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectHomeTypes'
                
  /project-foreign-types:
    get:
      summary: "Returns an array of possible project types for foreign projects"
      tags:
        - project foreign types
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectForeignTypes'
                
  /project:
    post:
      summary: 'Creates new project'
      tags:
        - project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: 'home'
                subtype:
                    type: string
                    example: 'KEGA'
                name_sk:
                  type: string
                  example: 'Názov projektu v slovenčine'
                name_eng:
                    type: string
                    example: 'Name of the project in english'
                abstract:
                  type: string
                  example: 'Convolutional neural networks (CNNs) have been applied to various automatic image segmentation tasks in medical image analysis, including brain MRI segmentation...'
                keywords:
                  type: array
                  items:
                    type: string
                    example: "Adversarial networks"
                start_date:
                  type: string
                  format: date-time
                  example: '2020-12-12'
                end_date:
                  type: string
                  format: date-time
                  example: '2021-12-12'
                milestones:
                  type: array
                  items: 
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 0
                      name: 
                        type: string
                        example: 'Milnik 1'
                      description:
                        type: string
                        example: 'Nejaky milnik, idk, laldaldaldlal.'
                      end_date:
                        type: string
                        format: date-time
                        example: '2021-12-12' 
                outputs:
                  type: array
                  items: 
                    type: object
                    properties:
                      name:
                        type: string
                        example: 'Patent'
                      count:
                        type: integer
                        example: 2
                      milestone_id:
                        type: integer
                        example: 0
                        
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewProject'
        '422':
          description: Unprocessable Entity
          #content:
          #  application/json:
          #    schema: 
          #      $ref:  '#/components/schemas/ErrorBadBody' 
                
components:
  schemas:
    ProjectStatuses:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 2
          status:
            type: string
            example: 'Pred schválením'
    
    ProjectHomeTypes:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 3
          status:
            type: string
            example: 'Grantový systém'
      
    ProjectForeignTypes:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            example: 3
          status:
            type: string
            example: 'Negrantové zmluvy'

    NewProject:
      type: object
      properties:
        id: 
          type: integer
          example: 2132134
